tutorial_animals_homepage:
    pattern:  /
    defaults: { _controller: TutorialAnimalsBundle:Default:index }

tutorial_animals_add:
    pattern:  /add
    defaults: { _controller: TutorialAnimalsBundle:Default:add }
