tutorial_animals_homepage:
    pattern:  /
    defaults: { _controller: TutorialAnimalsBundle:Default:index }

tutorial_animals_add:
    pattern:  /add
    defaults: { _controller: TutorialAnimalsBundle:Default:add }

tutorial_animals_Page:
    type: rest
    prefix: /v1
    resource: "Tutorial\AnimalsBundle\Controller\PageController"
    name_prefix:  api_1_ # naming collision
