parameters:
#    tutorial_animals.example.class: Tutorial\AnimalsBundle\Example

services:
#    tutorial_animals.example:
#        class: %tutorial_animals.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
