parameters:
#    acme_book.example.class: Acme\BookBundle\Example

services:
#    acme_book.example:
#        class: %acme_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
